<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0;net462</TargetFrameworks>
    <AssemblyName>MorseCode.ITask.Tests</AssemblyName>
    <RootNamespace>MorseCode.ITask.Tests</RootNamespace>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit.Console" Version="3.22.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="OpenCover" Version="4.7.1221" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\_Root\_Root.csproj" />
  </ItemGroup>

</Project>
